### ISSUE TITLE
400 error when uploading images

### ISSUE THREAD

**Issue by neurosie** [iliana/eggbug-rs#5]
My code: https://github.com/neurosie/primidi/blob/5b4bb264ac81783dd8dea2c98fd68a08ddd0bd8d/src/main.rs

I'm attaching one image, and when the post uploads I get the following error:
```
Error: Request(reqwest::Error { kind: Status(400), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("cohost.org")), port: None, path: "/api/v1/project/primidi/posts/1973428/attach/start", query: None, fragment: None } })
```

The post does appear on cohost, with an "invalid attachment" icon.

**Comment by iliana** [comment]
Are you using a version with this commit? https://github.com/iliana/eggbug-rs/commit/a7e164c313d18b7ac6f7b22dcc10283eb728078c

Sorry I haven’t made a new release with it yet. You can specify a git dependency in Cargo.toml: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

**Comment by neurosie** [comment]
Yes, I was using the cargo version. I switched to the github version and it works now. Thanks!
